### ISSUE TITLE
Support multiple VM

### ISSUE THREAD

**Issue by isnuryusuf** [umago/virtualbmc#5]
On your demo, you just have 1 VM, how about multiple VM, for example if i have 2 VM, how to manage VM1 and VM2 with ipmitool command

**Comment by aryulianto** [comment]
maybe u can use `--port` to managing multiple VM

example:
`vbmc add VM1 --username admin --password password --port 623`
`vbmc add VM2 --username admin --password password --port 624`

ipmitool command:
`ipmitool -I lanplus -U admin -P password -H 127.0.0.1 power status -p 623`
`ipmitool -I lanplus -U admin -P password -H 127.0.0.1 power status -p 624`

**Comment by isnuryusuf** [comment]
iam using this one
https://github.com/rhtyd/ipmisim
